services:
  - type: pserv
    name: temporal
    autoDeploy: false
    plan: Starter
    region: singapore
    env: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: SERVICES
        value: frontend,worker
      - key: DYNAMIC_CONFIG_FILE_PATH
        value: /etc/temporal/dynamicconfig.yaml
      - key: BIND_ON_IP
        value: 0.0.0.0
      - key: TEMPORAL_BROADCAST_ADDRESS
        value: 0.0.0.0
      - key: TEMPORAL_CLI_ADDRESS
        value: localhost:7233
  - type: web
    name: temporal-ui
    autoDeploy: false
    plan: Starter
    region: singapore
    env: docker
    dockerfilePath: ./web/Dockerfile
    envVars:
      - key: PORT
        value: 8088
      - key: TEMPORAL_PERMIT_WRITE_API
        value: true
      - key: TEMPORAL_GRPC_HOST
        fromService:
          name: temporal
          type: pserv
          property: host
  - type: web
    repo: https://github.com/render-examples/sample-temporal-app
    name: app-workflow-trigger
    plan: Starter
    region: singapore
    env: go
    buildCommand: go build start/main.go
    startCommand: ./main
    envVars:
      - key: TEMPORAL_CLUSTER_HOST
        fromService:
          name: temporal
          type: pserv
          property: host
  - type: worker
    repo: https://github.com/render-examples/sample-temporal-app
    name: app-worker
    plan: Starter
    region: oregon
    env: go
    buildCommand: go build worker/main.go
    startCommand: ./main
    envVars:
      - key: TEMPORAL_CLUSTER_HOST
        fromService:
          name: temporal
          type: pserv
          property: host
